zadatak dodat na granu
codejs2020/git-stefan pull request #1
Opened 2020-07-09 23:03 UTC by stefanljusic10

2020-07-11 12:42 UTC, lukautvic reviewed
Kad testiras, svaki put kad user unese broj koji pogodi, zamisljeni broj ti se menja.

dodaj ispod Math.random linije: console.log ('zamisljen broj', broj) da vidis i testiraj

2020-07-11 12:59 UTC, stefanljusic10 commented
> Kad testiras, svaki put kad user unese broj koji pogodi, zamisljeni broj ti se menja.
> 
> dodaj ispod Math.random linije: console.log ('zamisljen broj', broj) da vidis i testiraj

Nisam skontao da li radnom broj treba da bude isti tokom svih 5 pokusaja ili svaki put treba da se promeni?

2020-07-11 14:03 UTC, lukautvic commented
Svaki put isti. Kroz taj niz od 5 pokusaja, svaki put isti da bude zamisljen br

2020-07-12 09:55 UTC, lukautvic commented on src/nizovi.js
> +
Ponavljaju li se brojevi ovako?

2020-07-12 09:57 UTC, lukautvic commented on src/nizovi.js
> +
Ja bih rekao da se ponavljaju nakon testa, sad neka kaze neko drugi. Mozda sam i ja nesto lose odradio prilikom testiranja.

2020-07-12 10:51 UTC, frontend-comtrade requested changes

2020-07-12 10:51 UTC, frontend-comtrade commented on src/zadaci.js
>  // brojac klikova
Trebalo bi da onaj kod koji si podigao na master podigneš ovde da mogu da iskomentarišem. Kopiraj samo u drugi folder na ovoj grani i uradi push, nemoj da praviš nov pull request.

2020-07-12 10:51 UTC, frontend-comtrade commented on src/zadaci.js
>    let x = document.forma_random.num.value;  // x je promenljiva kojoj dodeljujemo vrednost koju korisnik unosi na ekranu u textbox-u
Čini mi se da ti linter nije uključen. 
```
npm install
npm run lint:js:fix
```
pa onda sve na git ponovo

2020-07-12 10:51 UTC, frontend-comtrade commented on src/zadaci.js
>  function randomBroj(){
Ova funkcija radi sve, osim onoga što joj ime kaže :)

2020-07-12 10:51 UTC, frontend-comtrade commented on src/zadaci.js
>    let x = document.forma_random.num.value;  // x je promenljiva kojoj dodeljujemo vrednost koju korisnik unosi na ekranu u textbox-u
Ovo sa pristupanjem preko name atributa se jako retko koristi i uglavnom se može naći u jako starim primerima. Promeni ga u document.getElementById ili document.querySelector

2020-07-12 10:51 UTC, frontend-comtrade commented on src/zadaci.js
> +// Funkcija koja prikazuje random broj
``` if(clickCount() < 5){```
može da se zameni sa
``` if(++counter <5){``` 
i onda možeš da izbrišeš clickCount funkciju

2020-07-12 10:51 UTC, frontend-comtrade commented on src/zadaci.js
> +// Funkcija koja prikazuje random broj
Možeš da napraviš funkciju ```poruka()``` koja bi kao parametar prihvatala tekst koji hoćeš da ispisuješ a koja bi upisivala u onaj gore id_ispis. na taj pozivi bi izgledali dosta čitljivije

2020-07-12 10:51 UTC, frontend-comtrade commented on src/index.html
> +  <label id="test"></label>
Šta radi ovaj label?
Dodaj title umesto ovog podrazumevanog.

2020-07-12 10:51 UTC, frontend-comtrade commented on src/index.html
>    <script src="zadaci.js"></script>
Kad završiš sve mogao bi da promeniš da ove putanje budu apsolutne (znači "/zadaci.js" i tome slično.

2020-07-12 10:51 UTC, frontend-comtrade commented on src/nizovi.js
> +  tekst = tekst.replace(/lj/g, 'љ');
`/lj/g` može da se napiše drugačije kao `new RegExp('lj','g')` tako da možeš da zameniš i napraviš sa nizom ponovo.

2020-07-12 10:51 UTC, frontend-comtrade commented on src/nizovi.js
>  function konverter(){
Koristi parametre i return.

2020-07-12 10:51 UTC, frontend-comtrade commented on src/nizovi.js
> +
Da, ponavljaju se.

2020-07-21 10:00 UTC, closed without merging